### ISSUE TITLE
Unable to predict using inference.py file

### ISSUE THREAD

**Issue by HsengivS** [xashru/punctuation-restoration#2]
I tried using the inference.py file to predict a sample text with 100 as sequence length, I get the following run time error. Kindly assist me on how this could be solved,

`python inference.py --pretrained-model=roberta-large --weight-path=roberta-large-en.pt --language=en  --in-file=data/test_en.txt --out-file=data/test_en_out.txt`

Traceback (most recent call last):
  **File "src/inference.py", line 106, in <module>
    inference()
  File "src/inference.py", line 42, in inference
    deep_punctuation.load_state_dict(torch.load(model_save_path))
  File "C:\Users\SMVP\Anaconda3\envs\my_torch\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepPunctuation:
        Missing key(s) in state_dict: "bert_layer.embeddings.position_ids".**

**Comment by xashru** [comment]
Hi,
Are you using `transformers==v2.11.0` ?

**Comment by k2m5t2** [comment]
I encountered the same error; installing transformers==v2.11.0 resolved it.

**Comment by FurkanGozukara** [comment]
I couldnt install transformers==v2.11.0

so it is a necessity :(

which python version is good for this?

**Comment by andbue** [comment]
Just in case someone else runs into this: according to https://github.com/huggingface/transformers/issues/16353, providing `strict=False` to `deep_punctuation.load_state_dict` simply ignores the missing keys, which allows other versions of transformers to load the models.
